### ISSUE TITLE
Does not work with Intellij 2020.3

### ISSUE THREAD

**Issue by kevchandler** [remotemobprogramming/intellij-mob#12]
I recently updated Intellij to 2020.3 and this plugin no longer works.  The VCS menu item in Intellij has been replaces with a Git menu item so I presume this has something to do with it.  There is no longer a Mob option anywhere in the menu.

If there is something I am doing wrong please let me know.  Otherwise are there plans to get it to work with this version?

**Comment by kevchandler** [comment]
That's good to hear.  Thanks

**Comment by christopher-nash** [comment]
As a temporary workaround I am able to see it from IntellJ's "universal launcher" dialog (Ctrl + Shift + A on Linux). If I search for `mob` then I see it listed. When I click it the start dialog does show up.

![image](https://user-images.githubusercontent.com/15619873/104755186-60831600-5717-11eb-9def-82908dceadb1.png)
![image](https://user-images.githubusercontent.com/15619873/104755228-6bd64180-5717-11eb-8222-f716595777c7.png)

Or there are shortcut you can use:
* `Alt + M, S` for **S**tart session
* `Alt + M, D` for **D**one with session

**Comment by nowsprinting** [comment]
Thank you for following up!
And I'm sorry for the late support 203.

There is also a shortcut, for "Next".
- `Alt + M, N`

**Comment by nowsprinting** [comment]
Sorry for being late.
Fixed in v1.0.3
