### ISSUE TITLE
Add developer documentation

### ISSUE THREAD

**Issue by McPringle** [remotemobprogramming/intellij-mob#19]
We would like to contribute to this plugin but had problems setting up the development environment. Can you please add some information on how to set up IntelliJ IDEA to be able to start and debug the plugin? That would be great!

**Comment by nowsprinting** [comment]
I don't have anything to add, as it should be possible to develop it with general documentations.

I am referring to the following documents and code.

* https://plugins.jetbrains.com/docs/intellij/welcome.html
* https://intellij-support.jetbrains.com/hc/en-us
* https://youtrack.jetbrains.com/issues/IJSDK
* https://github.com/JetBrains/intellij-community
* https://github.com/JetBrains/intellij-sdk-code-samples
