### ISSUE TITLE
Add plugin to intellij plugin repository

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/intellij-mob#4]
This would be awesome! Let me know if I can help.

**Comment by nowsprinting** [comment]
Thanks!
I already request to create repository, and the page was successfully created :tada:
https://plugins.jetbrains.com/plugin/14266-mob

I can't access settings page in this GitHub repository, now.
Please change my role or add plugin page url in repository header.

**Comment by nowsprinting** [comment]
One more thing,
I need access to setting page because add secret for GitHub Actions.

**Comment by simonharrer** [comment]
You should have access to everything now.

**Comment by nowsprinting** [comment]
Thanks!
