### ISSUE TITLE
Create plugin icon

### ISSUE THREAD

**Issue by nowsprinting** [remotemobprogramming/intellij-mob#6]
spec:
https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html

**Comment by nowsprinting** [comment]
@simonharrer san, Can you help me create plugin icon?

I has one (cheap!) Idea, to make a circle with mob logo?
Like this:
<img width="333" alt="circlemoblogo" src="https://user-images.githubusercontent.com/117617/81762886-beb48500-9508-11ea-9ec5-b4b99514821c.png">

**Comment by simonharrer** [comment]
@Ebano created the logo for the cli tool 'mob'. @Ebano do you think you could (and want) to help here?

**Comment by simonharrer** [comment]
We could use the icon for both, the intellij plugin and the cli tool when a square icon is necessary.

**Comment by Ebano** [comment]
I do :) will try something this week.

**Comment by nowsprinting** [comment]
Thanks!!

**Comment by Ebano** [comment]
How about this: 
![mob-logo_q](https://user-images.githubusercontent.com/17054348/82538525-2cd1fb00-9b4c-11ea-9604-341b8653d683.png)

If you like it, I can push the svg.

**Comment by Ebano** [comment]
(which is actually square)

**Comment by nowsprinting** [comment]
Thanks! I like the atmosphere.
What about the idea of making the purple arrow more circular?
I think it's can express cyclical typists of mob programming.

But, I don't understand what the original logo arrow means. 
If it has a different meaning, I think it's better to keep it.

**Comment by simonharrer** [comment]
the arrow means 'mob next'. Focus on the next, not the cycling through everybody (experts typically dont become typists). I like the logo.

**Comment by nowsprinting** [comment]
Thanks @simonharrer san, I understood means to arrow.
Let me use this logo!
@Ebano san, please put src/main/resources/META-INF/pluginIcon.svg to PR?

**Comment by nowsprinting** [comment]
merged #7 , Thanks!
