### ISSUE TITLE
Provide a version for IntelliJ 2020.2 EAP

### ISSUE THREAD

**Issue by L7R7** [remotemobprogramming/intellij-mob#9]
Version `1.0` of the plugin is not compatible with the 2020.2 EAP of IntelliJ. I don't know if there are some breaking API changes in IntelliJ that affect the plugin, but I would love to use the plugin in 2020.2

**Comment by nowsprinting** [comment]
Please wait a few days...

**Comment by nowsprinting** [comment]
Add support for 2020.2 in v1.0.1
https://plugins.jetbrains.com/plugin/14266-mob/update/90804
